# Generated by Django 4.2.6 on 2023-11-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='nombre',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
    ]
