# Generated by Django 4.2.6 on 2023-11-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_alter_curso_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='descripcion',
        ),
    ]
