# Generated by Django 4.2.6 on 2023-12-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_remove_contenido_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='video',
        ),
        migrations.AddField(
            model_name='contenido',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
