# Generated by Django 4.2.6 on 2023-11-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_remove_modulo_activo_remove_modulo_archivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
