# Generated by Django 4.2.6 on 2023-12-09 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_remove_contenido_archivo_remove_contenido_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='video_url',
            new_name='video',
        ),
    ]
