# Generated by Django 4.2.6 on 2023-11-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0007_remove_curso_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
