# Generated by Django 4.2.6 on 2023-11-19 04:30

from django.db import migrations
import userAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0008_curso_activo_modulo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='imagen',
            field=userAPI.models.APIImageField(blank=True, null=True, upload_to='contenidos/imagenes/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=userAPI.models.APIImageField(blank=True, null=True, upload_to='cursos/imagenes/'),
        ),
    ]
