# Generated by Django 4.2.6 on 2023-11-21 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0008_curso_activo_modulo_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='modulo',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProgresoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='no_iniciado', max_length=12)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_usuarios', to='userAPI.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_modulos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
