# Generated by Django 4.2.6 on 2023-11-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0008_curso_activo_modulo_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
