# Generated by Django 4.2.6 on 2023-11-20 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0009_rename_nombre_modulo_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
